// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | FiftyFiftySectionSlice
  | IntroBlockSlice
  | TestimonialsRowSlice
  | TeamSlice
  | GridSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >;

/**
 * Content for Person documents
 */
interface PersonDocumentData {
  /**
   * Picture field in *Person*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: person.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<'3:4'>;

  /**
   * Given name field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.givenName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  givenName: prismic.KeyTextField;

  /**
   * Surname field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.surname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  surname: prismic.KeyTextField;

  /**
   * Job title field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.jobTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  jobTitle: prismic.KeyTextField;

  /**
   * Summary field in *Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;
}

/**
 * Person document from Prismic
 *
 * - **API ID**: `person`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PersonDocumentData>, 'person', Lang>;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Background Color field in *Service*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: secondaryContainer
   * - **API ID Path**: service.backgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'secondaryContainer' | 'primaryContainer',
    'filled'
  >;

  /**
   * Picture field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<'4:3' | '1:1'>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    'service',
    Lang
  >;

/**
 * Content for Service Description documents
 */
interface ServiceDescriptionDocumentData {
  /**
   * Title field in *Service Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: serviceDescription.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Service Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: serviceDescription.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background Color field in *Service Description*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primaryContainer
   * - **API ID Path**: serviceDescription.backgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primaryContainer' | 'secondaryContainer',
    'filled'
  >;
}

/**
 * Service Description document from Prismic
 *
 * - **API ID**: `serviceDescription`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDescriptionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDescriptionDocumentData>,
    'serviceDescription',
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Given name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.givenName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  givenName: prismic.KeyTextField;

  /**
   * Text field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    'testimonial',
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PersonDocument
  | ServiceDocument
  | ServiceDescriptionDocument
  | TestimonialDocument;

/**
 * Primary content in *FiftyFiftySection → Default → Primary*
 */
export interface FiftyFiftySectionSliceDefaultPrimary {
  /**
   * Title field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Scroll Spy field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: fifty_fifty_section.default.primary.scrollSpy
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scrollSpy: prismic.SelectField<'false' | 'true', 'filled'>;

  /**
   * Background Color field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: fifty_fifty_section.default.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primary' | 'primaryContainer' | 'secondaryContainer',
    'filled'
  >;

  /**
   * Text field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'2:3'>;

  /**
   * Direction field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: start
   * - **API ID Path**: fifty_fifty_section.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<'start' | 'end', 'filled'>;
}

/**
 * Default variation for FiftyFiftySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FiftyFiftySectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FiftyFiftySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FiftyFiftySection*
 */
type FiftyFiftySectionSliceVariation = FiftyFiftySectionSliceDefault;

/**
 * FiftyFiftySection Shared Slice
 *
 * - **API ID**: `fifty_fifty_section`
 * - **Description**: FiftyFiftySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FiftyFiftySectionSlice = prismic.SharedSlice<
  'fifty_fifty_section',
  FiftyFiftySectionSliceVariation
>;

/**
 * Item in *ServicesGrid → Default → Primary → Items*
 */
export interface GridSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *ServicesGrid → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'service' | 'serviceDescription'>;
}

/**
 * Primary content in *ServicesGrid → Default → Primary*
 */
export interface GridSliceDefaultPrimary {
  /**
   * Title field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Scroll Spy field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: grid.default.primary.scrollSpy
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scrollSpy: prismic.SelectField<'false' | 'true', 'filled'>;

  /**
   * Items field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<GridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ServicesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesGrid*
 */
type GridSliceVariation = GridSliceDefault;

/**
 * ServicesGrid Shared Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Grid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSlice = prismic.SharedSlice<'grid', GridSliceVariation>;

/**
 * Primary content in *IntroBlock → Default → Primary*
 */
export interface IntroBlockSliceDefaultPrimary {
  /**
   * Title field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Scroll Spy field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: intro_block.default.primary.scrollSpy
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scrollSpy: prismic.SelectField<'false' | 'true', 'filled'>;

  /**
   * Content field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for IntroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<IntroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroBlock*
 */
type IntroBlockSliceVariation = IntroBlockSliceDefault;

/**
 * IntroBlock Shared Slice
 *
 * - **API ID**: `intro_block`
 * - **Description**: IntroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSlice = prismic.SharedSlice<
  'intro_block',
  IntroBlockSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Items*
 */
export interface TeamSliceDefaultPrimaryItemsItem {
  /**
   * Person field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[].person
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  person: prismic.ContentRelationshipField<'person'>;

  /**
   * Direction field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: start
   * - **API ID Path**: team.default.primary.items[].direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<'start' | 'end', 'filled'>;

  /**
   * Background Color field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primaryContainer
   * - **API ID Path**: team.default.primary.items[].backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primaryContainer' | 'secondaryContainer',
    'filled'
  >;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Scroll Spy field in *Team → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: team.default.primary.scrollSpy
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scrollSpy: prismic.SelectField<'false' | 'true', 'filled'>;

  /**
   * Items field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<'team', TeamSliceVariation>;

/**
 * Item in *TestimonialsRow → Default → Primary → Items*
 */
export interface TestimonialsRowSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *TestimonialsRow → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_row.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'testimonial'>;
}

/**
 * Primary content in *TestimonialsRow → Default → Primary*
 */
export interface TestimonialsRowSliceDefaultPrimary {
  /**
   * Items field in *TestimonialsRow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_row.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<TestimonialsRowSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for TestimonialsRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsRowSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsRowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialsRow*
 */
type TestimonialsRowSliceVariation = TestimonialsRowSliceDefault;

/**
 * TestimonialsRow Shared Slice
 *
 * - **API ID**: `testimonials_row`
 * - **Description**: TestimonialsRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsRowSlice = prismic.SharedSlice<
  'testimonials_row',
  TestimonialsRowSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PersonDocument,
      PersonDocumentData,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDescriptionDocument,
      ServiceDescriptionDocumentData,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      FiftyFiftySectionSlice,
      FiftyFiftySectionSliceDefaultPrimary,
      FiftyFiftySectionSliceVariation,
      FiftyFiftySectionSliceDefault,
      GridSlice,
      GridSliceDefaultPrimaryItemsItem,
      GridSliceDefaultPrimary,
      GridSliceVariation,
      GridSliceDefault,
      IntroBlockSlice,
      IntroBlockSliceDefaultPrimary,
      IntroBlockSliceVariation,
      IntroBlockSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryItemsItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialsRowSlice,
      TestimonialsRowSliceDefaultPrimaryItemsItem,
      TestimonialsRowSliceDefaultPrimary,
      TestimonialsRowSliceVariation,
      TestimonialsRowSliceDefault,
    };
  }
}
