// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Course Sessions → Items*
 */
export interface CourseSessionsDocumentDataItemsItem {
  /**
   * Label field in *Course Sessions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courseSessions.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *Course Sessions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courseSessions.items[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;
}

/**
 * Content for Course Sessions documents
 */
interface CourseSessionsDocumentData {
  /**
   * Items field in *Course Sessions*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: courseSessions.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<CourseSessionsDocumentDataItemsItem>>;
}

/**
 * Course Sessions document from Prismic
 *
 * - **API ID**: `courseSessions`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CourseSessionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CourseSessionsDocumentData>,
    'courseSessions',
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | ContactsSlice
  | FiftyFiftySectionSlice
  | IntroBlockSlice
  | TestimonialsRowSlice
  | TeamSlice
  | GridSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.metaTitle
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaTitle: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.metaDescription
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaImage
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >;

/**
 * Item in *Main Navigation → Items*
 */
export interface MainNavigationDocumentDataItemsItem {
  /**
   * Item field in *Main Navigation → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: mainNavigation.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'page' | 'homepage'>;
}

/**
 * Content for Main Navigation documents
 */
interface MainNavigationDocumentData {
  /**
   * Items field in *Main Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mainNavigation.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<MainNavigationDocumentDataItemsItem>>;
}

/**
 * Main Navigation document from Prismic
 *
 * - **API ID**: `mainNavigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainNavigationDocumentData>,
    'mainNavigation',
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | MediaBannerSlice
  | ListItemsSlice
  | ContactsSlice
  | FiftyFiftySectionSlice
  | IntroBlockSlice
  | TestimonialsRowSlice
  | TeamSlice
  | GridSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Navigation label field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label used in navigation menu
   * - **API ID Path**: page.navigationLabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  navigationLabel: prismic.KeyTextField;

  /**
   * Tint field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: page.tint
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tint: prismic.SelectField<'primary' | 'secondary', 'filled'>;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.metaTitle
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaTitle: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.metaDescription
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaImage
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

/**
 * Content for Person documents
 */
interface PersonDocumentData {
  /**
   * Picture field in *Person*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: person.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<'3:4'>;

  /**
   * Given name field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.givenName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  givenName: prismic.KeyTextField;

  /**
   * Surname field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.surname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  surname: prismic.KeyTextField;

  /**
   * Job title field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.jobTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  jobTitle: prismic.KeyTextField;

  /**
   * Summary field in *Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;
}

/**
 * Person document from Prismic
 *
 * - **API ID**: `person`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PersonDocumentData>, 'person', Lang>;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Background Color field in *Service*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: secondaryContainer
   * - **API ID Path**: service.backgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'secondaryContainer' | 'primaryContainer',
    'filled'
  >;

  /**
   * Picture field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<'4:3' | '1:1'>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    'service',
    Lang
  >;

/**
 * Content for Service Description documents
 */
interface ServiceDescriptionDocumentData {
  /**
   * Title field in *Service Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: serviceDescription.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Service Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: serviceDescription.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background Color field in *Service Description*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primaryContainer
   * - **API ID Path**: serviceDescription.backgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primaryContainer' | 'secondaryContainer',
    'filled'
  >;
}

/**
 * Service Description document from Prismic
 *
 * - **API ID**: `serviceDescription`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDescriptionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDescriptionDocumentData>,
    'serviceDescription',
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Given name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.givenName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  givenName: prismic.KeyTextField;

  /**
   * Text field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    'testimonial',
    Lang
  >;

export type AllDocumentTypes =
  | CourseSessionsDocument
  | HomepageDocument
  | MainNavigationDocument
  | PageDocument
  | PersonDocument
  | ServiceDocument
  | ServiceDescriptionDocument
  | TestimonialDocument;

/**
 * Item in *Contacts → Default → Primary → Form*
 */
export interface ContactsSliceDefaultPrimaryFormItem {
  /**
   * Field Type field in *Contacts → Default → Primary → Form*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: textField
   * - **API ID Path**: contacts.default.primary.form[].fieldType
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  fieldType: prismic.SelectField<'textField' | 'select' | 'textarea', 'filled'>;

  /**
   * Field Name field in *Contacts → Default → Primary → Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.form[].fieldName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fieldName: prismic.KeyTextField;

  /**
   * Field Label field in *Contacts → Default → Primary → Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.form[].fieldLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fieldLabel: prismic.KeyTextField;

  /**
   * Required field in *Contacts → Default → Primary → Form*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: contacts.default.primary.form[].required
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  required: prismic.BooleanField;

  /**
   * Field Meta field in *Contacts → Default → Primary → Form*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.form[].fieldMeta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  fieldMeta: prismic.ContentRelationshipField<'courseSessions'>;
}

/**
 * Primary content in *Contacts → Default → Primary*
 */
export interface ContactsSliceDefaultPrimary {
  /**
   * Title field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contacts.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Form field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.form[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  form: prismic.GroupField<Simplify<ContactsSliceDefaultPrimaryFormItem>>;

  /**
   * Localisation field in *Contacts → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.localisation
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  localisation: prismic.GeoPointField;

  /**
   * Information field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.information
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  information: prismic.RichTextField;

  /**
   * Background Color field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: contacts.default.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primary' | 'secondaryContainer',
    'filled'
  >;

  /**
   * Form Type field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: message
   * - **API ID Path**: contacts.default.primary.formType
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  formType: prismic.SelectField<'message' | 'inscription', 'filled'>;
}

/**
 * Default variation for Contacts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContactsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contacts*
 */
type ContactsSliceVariation = ContactsSliceDefault;

/**
 * Contacts Shared Slice
 *
 * - **API ID**: `contacts`
 * - **Description**: Contacts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsSlice = prismic.SharedSlice<
  'contacts',
  ContactsSliceVariation
>;

/**
 * Primary content in *FiftyFiftySection → Default → Primary*
 */
export interface FiftyFiftySectionSliceDefaultPrimary {
  /**
   * Title field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: fifty_fifty_section.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Background Color field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: fifty_fifty_section.default.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primary' | 'primaryContainer' | 'secondaryContainer',
    'filled'
  >;

  /**
   * Text field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fifty_fifty_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'2:3'>;

  /**
   * Direction field in *FiftyFiftySection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: start
   * - **API ID Path**: fifty_fifty_section.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<'start' | 'end', 'filled'>;
}

/**
 * Default variation for FiftyFiftySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FiftyFiftySectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FiftyFiftySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FiftyFiftySection*
 */
type FiftyFiftySectionSliceVariation = FiftyFiftySectionSliceDefault;

/**
 * FiftyFiftySection Shared Slice
 *
 * - **API ID**: `fifty_fifty_section`
 * - **Description**: FiftyFiftySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FiftyFiftySectionSlice = prismic.SharedSlice<
  'fifty_fifty_section',
  FiftyFiftySectionSliceVariation
>;

/**
 * Item in *ServicesGrid → Default → Primary → Items*
 */
export interface GridSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *ServicesGrid → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'service' | 'serviceDescription'>;
}

/**
 * Primary content in *ServicesGrid → Default → Primary*
 */
export interface GridSliceDefaultPrimary {
  /**
   * Title field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: grid.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Items field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<GridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ServicesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesGrid*
 */
type GridSliceVariation = GridSliceDefault;

/**
 * ServicesGrid Shared Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Grid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSlice = prismic.SharedSlice<'grid', GridSliceVariation>;

/**
 * Item in *IntroBlock → With Link to Media → Primary → CTA*
 */
export interface IntroBlockSliceWithLinkToMediaPrimaryCtaItem {
  /**
   * Label field in *IntroBlock → With Link to Media → Primary → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.withLinkToMedia.primary.cta[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Media field in *IntroBlock → With Link to Media → Primary → CTA*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.withLinkToMedia.primary.cta[].media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField;

  /**
   * Variant field in *IntroBlock → With Link to Media → Primary → CTA*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: filled
   * - **API ID Path**: intro_block.withLinkToMedia.primary.cta[].variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<
    'filled' | 'outlined' | 'bare' | 'ghost',
    'filled'
  >;
}

/**
 * Primary content in *IntroBlock → Default → Primary*
 */
export interface IntroBlockSliceDefaultPrimary {
  /**
   * Title field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: intro_block.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Text field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Background Color field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: intro_block.default.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primary' | 'secondaryContainer',
    'filled'
  >;
}

/**
 * Default variation for IntroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<IntroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *IntroBlock → With Link to Media → Primary*
 */
export interface IntroBlockSliceWithLinkToMediaPrimary {
  /**
   * Title field in *IntroBlock → With Link to Media → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.withLinkToMedia.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *IntroBlock → With Link to Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: intro_block.withLinkToMedia.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *IntroBlock → With Link to Media → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.withLinkToMedia.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *IntroBlock → With Link to Media → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.withLinkToMedia.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Text field in *IntroBlock → With Link to Media → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.withLinkToMedia.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Background Color field in *IntroBlock → With Link to Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: intro_block.withLinkToMedia.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primary' | 'secondaryContainer',
    'filled'
  >;

  /**
   * CTA field in *IntroBlock → With Link to Media → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.withLinkToMedia.primary.cta[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta: prismic.GroupField<
    Simplify<IntroBlockSliceWithLinkToMediaPrimaryCtaItem>
  >;
}

/**
 * With Link to Media variation for IntroBlock Slice
 *
 * - **API ID**: `withLinkToMedia`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSliceWithLinkToMedia = prismic.SharedSliceVariation<
  'withLinkToMedia',
  Simplify<IntroBlockSliceWithLinkToMediaPrimary>,
  never
>;

/**
 * Slice variation for *IntroBlock*
 */
type IntroBlockSliceVariation =
  | IntroBlockSliceDefault
  | IntroBlockSliceWithLinkToMedia;

/**
 * IntroBlock Shared Slice
 *
 * - **API ID**: `intro_block`
 * - **Description**: IntroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlockSlice = prismic.SharedSlice<
  'intro_block',
  IntroBlockSliceVariation
>;

/**
 * Item in *ListItems → Default → Primary → Items*
 */
export interface ListItemsSliceDefaultPrimaryItemsItem {
  /**
   * Label field in *ListItems → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list_items.default.primary.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *ListItems → Default → Primary*
 */
export interface ListItemsSliceDefaultPrimary {
  /**
   * Title field in *ListItems → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list_items.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *ListItems → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: list_items.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *ListItems → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list_items.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *ListItems → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list_items.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Background Color field in *ListItems → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: secondaryContainer
   * - **API ID Path**: list_items.default.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'secondaryContainer' | 'primaryContainer' | 'primary',
    'filled'
  >;

  /**
   * Items field in *ListItems → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: list_items.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<ListItemsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ListItems Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListItemsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ListItemsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ListItems*
 */
type ListItemsSliceVariation = ListItemsSliceDefault;

/**
 * ListItems Shared Slice
 *
 * - **API ID**: `list_items`
 * - **Description**: ListItems
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListItemsSlice = prismic.SharedSlice<
  'list_items',
  ListItemsSliceVariation
>;

/**
 * Item in *MediaBanner → Default → Primary → Items*
 */
export interface MediaBannerSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *MediaBanner → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *MediaBanner → Default → Primary → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: media_banner.default.primary.items[].subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *MediaBanner → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.items[].subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *MediaBanner → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.items[].slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Content field in *MediaBanner → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *MediaBanner → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'16:9' | '2:3'>;

  /**
   * Direction field in *MediaBanner → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: start
   * - **API ID Path**: media_banner.default.primary.items[].direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<'start' | 'end', 'filled'>;
}

/**
 * Primary content in *MediaBanner → Default → Primary*
 */
export interface MediaBannerSliceDefaultPrimary {
  /**
   * Title field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: media_banner.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Content field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'16:9' | '2:3'>;

  /**
   * Direction field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: start
   * - **API ID Path**: media_banner.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<'start' | 'end', 'filled'>;

  /**
   * Items field in *MediaBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: media_banner.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<MediaBannerSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for MediaBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaBannerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MediaBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MediaBanner*
 */
type MediaBannerSliceVariation = MediaBannerSliceDefault;

/**
 * MediaBanner Shared Slice
 *
 * - **API ID**: `media_banner`
 * - **Description**: MediaBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaBannerSlice = prismic.SharedSlice<
  'media_banner',
  MediaBannerSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Items*
 */
export interface TeamSliceDefaultPrimaryItemsItem {
  /**
   * Person field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[].person
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  person: prismic.ContentRelationshipField<'person'>;

  /**
   * Direction field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: start
   * - **API ID Path**: team.default.primary.items[].direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<'start' | 'end', 'filled'>;

  /**
   * Background Color field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primaryContainer
   * - **API ID Path**: team.default.primary.items[].backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColor: prismic.SelectField<
    'primaryContainer' | 'secondaryContainer',
    'filled'
  >;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *Team → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: team.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Items field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<'team', TeamSliceVariation>;

/**
 * Item in *TestimonialsRow → Default → Primary → Items*
 */
export interface TestimonialsRowSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *TestimonialsRow → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_row.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'testimonial'>;

  /**
   * Tint Scheme field in *TestimonialsRow → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: secondaryContainer
   * - **API ID Path**: testimonials_row.default.primary.items[].tintScheme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tintScheme: prismic.SelectField<
    'secondaryContainer' | 'primaryContainer',
    'filled'
  >;
}

/**
 * Primary content in *TestimonialsRow → Default → Primary*
 */
export interface TestimonialsRowSliceDefaultPrimary {
  /**
   * Title field in *TestimonialsRow → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_row.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Show in Sub Navigation field in *TestimonialsRow → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: testimonials_row.default.primary.subNavigation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  subNavigation: prismic.BooleanField;

  /**
   * Sub Navigation Label field in *TestimonialsRow → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_row.default.primary.subNavigationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subNavigationLabel: prismic.KeyTextField;

  /**
   * Slug field in *TestimonialsRow → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_row.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Items field in *TestimonialsRow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_row.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<TestimonialsRowSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for TestimonialsRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsRowSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsRowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialsRow*
 */
type TestimonialsRowSliceVariation = TestimonialsRowSliceDefault;

/**
 * TestimonialsRow Shared Slice
 *
 * - **API ID**: `testimonials_row`
 * - **Description**: TestimonialsRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsRowSlice = prismic.SharedSlice<
  'testimonials_row',
  TestimonialsRowSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CourseSessionsDocument,
      CourseSessionsDocumentData,
      CourseSessionsDocumentDataItemsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MainNavigationDocument,
      MainNavigationDocumentData,
      MainNavigationDocumentDataItemsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PersonDocument,
      PersonDocumentData,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDescriptionDocument,
      ServiceDescriptionDocumentData,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      ContactsSlice,
      ContactsSliceDefaultPrimaryFormItem,
      ContactsSliceDefaultPrimary,
      ContactsSliceVariation,
      ContactsSliceDefault,
      FiftyFiftySectionSlice,
      FiftyFiftySectionSliceDefaultPrimary,
      FiftyFiftySectionSliceVariation,
      FiftyFiftySectionSliceDefault,
      GridSlice,
      GridSliceDefaultPrimaryItemsItem,
      GridSliceDefaultPrimary,
      GridSliceVariation,
      GridSliceDefault,
      IntroBlockSlice,
      IntroBlockSliceDefaultPrimary,
      IntroBlockSliceWithLinkToMediaPrimaryCtaItem,
      IntroBlockSliceWithLinkToMediaPrimary,
      IntroBlockSliceVariation,
      IntroBlockSliceDefault,
      IntroBlockSliceWithLinkToMedia,
      ListItemsSlice,
      ListItemsSliceDefaultPrimaryItemsItem,
      ListItemsSliceDefaultPrimary,
      ListItemsSliceVariation,
      ListItemsSliceDefault,
      MediaBannerSlice,
      MediaBannerSliceDefaultPrimaryItemsItem,
      MediaBannerSliceDefaultPrimary,
      MediaBannerSliceVariation,
      MediaBannerSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryItemsItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialsRowSlice,
      TestimonialsRowSliceDefaultPrimaryItemsItem,
      TestimonialsRowSliceDefaultPrimary,
      TestimonialsRowSliceVariation,
      TestimonialsRowSliceDefault,
    };
  }
}
