// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | IntroBlocSlice
  | TestimonialsSlice
  | TeamSlice
  | GridSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >;

/**
 * Content for Person documents
 */
interface PersonDocumentData {
  /**
   * Picture field in *Person*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: person.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<'xl' | 'md' | 'sm'>;

  /**
   * Given name field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.given_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  given_name: prismic.KeyTextField;

  /**
   * Surname field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.surname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  surname: prismic.KeyTextField;

  /**
   * Job title field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Summary field in *Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;
}

/**
 * Person document from Prismic
 *
 * - **API ID**: `person`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PersonDocumentData>, 'person', Lang>;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Background Color field in *Service*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: secondary
   * - **API ID Path**: service.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<'secondary' | 'primary', 'filled'>;

  /**
   * Picture field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<'4:3' | '1:1'>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    'service',
    Lang
  >;

/**
 * Content for Service Description documents
 */
interface ServiceDescriptionDocumentData {
  /**
   * Title field in *Service Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_description.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Service Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_description.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background Color field in *Service Description*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: service_description.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<'primary' | 'secondary', 'filled'>;
}

/**
 * Service Description document from Prismic
 *
 * - **API ID**: `service_description`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDescriptionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDescriptionDocumentData>,
    'service_description',
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Given name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.given_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  given_name: prismic.KeyTextField;

  /**
   * Content field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    'testimonial',
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PersonDocument
  | ServiceDocument
  | ServiceDescriptionDocument
  | TestimonialDocument;

/**
 * Item in *ServicesGrid → Default → Primary → Items*
 */
export interface GridSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *ServicesGrid → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'service' | 'service_description'>;
}

/**
 * Primary content in *ServicesGrid → Default → Primary*
 */
export interface GridSliceDefaultPrimary {
  /**
   * Items field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<GridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ServicesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesGrid*
 */
type GridSliceVariation = GridSliceDefault;

/**
 * ServicesGrid Shared Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Grid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSlice = prismic.SharedSlice<'grid', GridSliceVariation>;

/**
 * Primary content in *IntroBloc → Default → Primary*
 */
export interface IntroBlocSliceDefaultPrimary {
  /**
   * Title field in *IntroBloc → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_bloc.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *IntroBloc → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_bloc.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for IntroBloc Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlocSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<IntroBlocSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroBloc*
 */
type IntroBlocSliceVariation = IntroBlocSliceDefault;

/**
 * IntroBloc Shared Slice
 *
 * - **API ID**: `intro_bloc`
 * - **Description**: IntroBloc
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroBlocSlice = prismic.SharedSlice<
  'intro_bloc',
  IntroBlocSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Items*
 */
export interface TeamSliceDefaultPrimaryItemsItem {
  /**
   * item field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'person'>;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Items field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<'team', TeamSliceVariation>;

/**
 * Item in *TestimonialsRow → Default → Primary → Items*
 */
export interface TestimonialsSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *TestimonialsRow → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<'testimonial'>;
}

/**
 * Primary content in *TestimonialsRow → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Items field in *TestimonialsRow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for TestimonialsRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialsRow*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * TestimonialsRow Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  'testimonials',
  TestimonialsSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PersonDocument,
      PersonDocumentData,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDescriptionDocument,
      ServiceDescriptionDocumentData,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      GridSlice,
      GridSliceDefaultPrimaryItemsItem,
      GridSliceDefaultPrimary,
      GridSliceVariation,
      GridSliceDefault,
      IntroBlocSlice,
      IntroBlocSliceDefaultPrimary,
      IntroBlocSliceVariation,
      IntroBlocSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryItemsItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryItemsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
