// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  contacts: dynamic(() => import('./Contacts')),
  fifty_fifty_section: dynamic(() => import('./FiftyFiftySection')),
  grid: dynamic(() => import('./ServicesGrid')),
  intro_block: dynamic(() => import('./IntroBlock')),
  team: dynamic(() => import('./Team')),
  testimonials_row: dynamic(() => import('./TestimonialsRow')),
};
