// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  grid: dynamic(() => import('./ServicesGrid')),
  intro_bloc: dynamic(() => import('./IntroBloc')),
  team: dynamic(() => import('./Team')),
  testimonials: dynamic(() => import('./TestimonialsRow')),
};
